//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoLlavero
    {
        public int id { get; set; }
        public string nro_llave { get; set; }
        public string estado { get; set; }
        public Nullable<int> ticket { get; set; }
        public string matricula { get; set; }
    }
}
