//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoParking
    {
        public int id { get; set; }
        public string str_fecha_entrada { get; set; }
        public string str_fecha_salida { get; set; }
        public string str_hora_entrada { get; set; }
        public string str_hora_salida { get; set; }
        public int id_tipo_movimiento { get; set; }
        public Nullable<int> id_tipo_vehiculo { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public decimal dob_importe { get; set; }
        public Nullable<int> id_vehiculo_registrado { get; set; }
        public string str_matricula { get; set; }
        public string str_observaciones { get; set; }
        public Nullable<int> id_convenio { get; set; }
        public Nullable<int> id_pension { get; set; }
        public string str_desde_fecha_pension { get; set; }
        public string str_hasta_fecha_pension { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_movimiento_caja { get; set; }
        public Nullable<int> creditos_generados { get; set; }
        public Nullable<bool> creditos_usados { get; set; }
    }
}
