//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosCaja
    {
        public int id { get; set; }
        public string str_fecha { get; set; }
        public string str_hora { get; set; }
        public decimal importe { get; set; }
        public bool cerrado { get; set; }
        public Nullable<int> id_referencia_cierre { get; set; }
        public Nullable<int> id_tipo_movimiento { get; set; }
        public string str_eliminado { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_tipo_documento_emision { get; set; }
        public Nullable<int> correlativo_documento_emision { get; set; }
        public string serie_documento_emision { get; set; }
        public Nullable<int> rollo { get; set; }
        public string rut { get; set; }
        public string razon_social { get; set; }
        public string str_observaciones { get; set; }
        public Nullable<int> correlativo_ticket { get; set; }
        public string str_tipo_vehiculo { get; set; }
        public string str_convenio { get; set; }
        public Nullable<int> minutos { get; set; }
        public Nullable<decimal> importe_calculado { get; set; }
        public Nullable<decimal> valor_comision { get; set; }
        public Nullable<bool> com_cobrada { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
