//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifa
    {
        public int id { get; set; }
        public int id_tipo_vehiculo { get; set; }
        public string str_tarifa { get; set; }
        public int minutos { get; set; }
        public int minutos_tolerancia { get; set; }
        public decimal importe { get; set; }
        public bool techo { get; set; }
        public int id_convenio { get; set; }
    
        public virtual TipoVehiculo TipoVehiculo { get; set; }
    }
}
