//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumentoEmision_Correlativos
    {
        public int id { get; set; }
        public string str_codigo { get; set; }
        public string str_descrip { get; set; }
        public int int_correlativo_prox { get; set; }
    }
}
