//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Adentroes = new HashSet<Adentro>();
            this.MovimientosCajas = new HashSet<MovimientosCaja>();
        }
    
        public int id { get; set; }
        public string str_nombre_usuario { get; set; }
        public string str_password { get; set; }
        public int id_rol { get; set; }
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string ci { get; set; }
        public string fecha_ingreso { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public Nullable<decimal> remuneracion_nominal { get; set; }
        public Nullable<bool> permiso_principa { get; set; }
        public Nullable<bool> permiso_es { get; set; }
        public Nullable<bool> permiso_agregar_mov_caja { get; set; }
        public Nullable<bool> permiso_nota_credito { get; set; }
        public Nullable<bool> permiso_pensionistas { get; set; }
        public Nullable<bool> permiso_cc { get; set; }
        public Nullable<bool> permiso_agregar_mov_cc { get; set; }
        public Nullable<bool> permiso_cobrar_pensiones { get; set; }
        public Nullable<bool> permiso_emitir_facturacion_mensual { get; set; }
        public Nullable<bool> permiso_parametricas { get; set; }
        public Nullable<bool> permiso_usuarios { get; set; }
        public Nullable<bool> permiso_configurador { get; set; }
        public Nullable<bool> permiso_respaldo { get; set; }
        public Nullable<bool> permiso_reportes { get; set; }
        public Nullable<bool> permiso_estadisticas { get; set; }
        public Nullable<bool> permiso_obligar_login_cierre_caja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adentro> Adentroes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientosCaja> MovimientosCajas { get; set; }
    }
}
