//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculosRegistrado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehiculosRegistrado()
        {
            this.VehiculosPensions = new HashSet<VehiculosPension>();
        }
    
        public int id { get; set; }
        public int id_modelo { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string str_matricula { get; set; }
        public string str_marca_modelo { get; set; }
        public string nombre_cliente { get; set; }
        public string rut { get; set; }
        public string razon_social { get; set; }
        public string ci { get; set; }
        public string email { get; set; }
        public string direccion { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string cel1 { get; set; }
        public string cel2 { get; set; }
        public string observaciones { get; set; }
        public string autorizado1_ci { get; set; }
        public string autorizado2_ci { get; set; }
        public string autorizado3_ci { get; set; }
        public string autorizado1_nombres { get; set; }
        public string autorizado2_nombres { get; set; }
        public string autorizado3_nombres { get; set; }
        public string autorizado1_apellidos { get; set; }
        public string autorizado2_apellidos { get; set; }
        public string autorizado3_apellidos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiculosPension> VehiculosPensions { get; set; }
    }
}
