//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking40_ExpendedorBarrera
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENCE
    {
        public int ID { get; set; }
        public Nullable<int> LOCATIONID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SourcePath { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Recognition_Left { get; set; }
        public Nullable<int> Recognition_Top { get; set; }
        public Nullable<int> Recognition_Width { get; set; }
        public Nullable<int> Recognition_Height { get; set; }
        public Nullable<int> NumSteps { get; set; }
        public Nullable<int> MinStep { get; set; }
        public Nullable<int> MaxStep { get; set; }
        public Nullable<double> DistanceCoeff { get; set; }
        public Nullable<double> HorizontalCoeff { get; set; }
        public Nullable<double> VerticalCoeff { get; set; }
        public Nullable<double> AngleCoeff { get; set; }
        public Nullable<int> CharacterSize { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<double> GpsLatitude { get; set; }
        public Nullable<double> GpsLongitude { get; set; }
        public Nullable<int> ApplyCorrection { get; set; }
        public Nullable<int> STATUSID { get; set; }
        public Nullable<int> TYPEINCIDENCEID { get; set; }
        public Nullable<int> Sent { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Class { get; set; }
        public string Brand { get; set; }
        public string Color { get; set; }
        public string Cause_N_Notification { get; set; }
        public Nullable<int> NName { get; set; }
        public string Agent { get; set; }
        public string Precept { get; set; }
        public Nullable<double> IMP_REDUCED { get; set; }
        public Nullable<double> IMP_NOT_REDUCED { get; set; }
        public int Export { get; set; }
        public int ExportImages { get; set; }
        public string IDGestPol { get; set; }
        public Nullable<System.DateTime> DateValidation { get; set; }
        public int camera_id { get; set; }
        public int computerID { get; set; }
        public string Result_Send { get; set; }
        public int Send_Server { get; set; }
        public System.DateTime Date_Send_Server { get; set; }
    }
}
